In [1]:
#Importing Pandas
import pandas as pd

In [2]:
#Reading csv file
df = pd.read_csv("car_prices.csv")

In [3]:
df

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558832,2015,Kia,K900,Luxury,Sedan,NaN,knalw4d4xf6019304,in,45.0,18255.0,silver,black,avis corporation,35300.0,33000.0,Thu Jul 09 2015 07:00:00 GMT-0700 (PDT)
558833,2012,Ram,2500,Power Wagon,Crew Cab,automatic,3c6td5et6cg112407,wa,5.0,54393.0,white,black,i -5 uhlmann rv,30200.0,30800.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558834,2012,BMW,X5,xDrive35d,SUV,automatic,5uxzw0c58cl668465,ca,48.0,50561.0,black,black,financial services remarketing (lease),29800.0,34000.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558835,2015,Nissan,Altima,2.5 S,sedan,automatic,1n4al3ap0fc216050,ga,38.0,16658.0,white,black,enterprise vehicle exchange / tra / rental / t...,15100.0,11100.0,Thu Jul 09 2015 06:45:00 GMT-0700 (PDT)
558836,2014,Ford,F-150,XLT,SuperCrew,automatic,1ftfw1et2eke87277,ca,34.0,15008.0,gray,gray,ford motor credit company llc pd,29600.0,26700.0,Thu May 28 2015 05:30:00 GMT-0700 (PDT)

In [4]:
#Uppecasing VIN-numbers:
df["vin"] = df["vin"].str.upper()

In [5]:
#Capitalizing column names
df.columns = [col.capitalize() for col in df.columns]
df.columns

Index(['Year', 'Make', 'Model', 'Trim', 'Body', 'Transmission', 'Vin', 'State',
       'Condition', 'Odometer', 'Color', 'Interior', 'Seller', 'Mmr',
       'Sellingprice', 'Saledate'],
      dtype='object')

In [6]:
df.head(5)

,Year,Make,Model,Trim,Body,Transmission,Vin,State,Condition,Odometer,Color,Interior,Seller,Mmr,Sellingprice,Saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5XYKTCA69FG566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5XYKTCA69FG561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,WBA3C1C51EK116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,YV1612TB4F1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,WBA6B2C57ED129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [7]:
#Renaming columns for better readability
df.rename(columns = {"Mmr": "MMR", "Sellingprice": "Selling_Price", "Saledate": "Sale_Date", "Vin": "VIN"}, inplace = True)

In [8]:
#Uppercasing State
df["State"] = df["State"].str.upper()

In [9]:
#capitalizing each word in Seller column:
df["Seller"] = df["Seller"].str.title()

In [10]:
df

,Year,Make,Model,Trim,Body,Transmission,VIN,State,Condition,Odometer,Color,Interior,Seller,MMR,Selling_Price,Sale_Date
0,2015,Kia,Sorento,LX,SUV,automatic,5XYKTCA69FG566472,CA,5.0,16639.0,white,black,Kia Motors America Inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5XYKTCA69FG561319,CA,5.0,9393.0,white,beige,Kia Motors America Inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,WBA3C1C51EK116351,CA,45.0,1331.0,gray,black,Financial Services Remarketing (Lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,YV1612TB4F1310987,CA,41.0,14282.0,white,black,Volvo Na Rep/World Omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,WBA6B2C57ED129731,CA,43.0,2641.0,gray,black,Financial Services Remarketing (Lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558832,2015,Kia,K900,Luxury,Sedan,NaN,KNALW4D4XF6019304,IN,45.0,18255.0,silver,black,Avis Corporation,35300.0,33000.0,Thu Jul 09 2015 07:00:00 GMT-0700 (PDT)
558833,2012,Ram,2500,Power Wagon,Crew Cab,automatic,3C6TD5ET6CG112407,WA,5.0,54393.0,white,black,I -5 Uhlmann Rv,30200.0,30800.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558834,2012,BMW,X5,xDrive35d,SUV,automatic,5UXZW0C58CL668465,CA,48.0,50561.0,black,black,Financial Services Remarketing (Lease),29800.0,34000.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558835,2015,Nissan,Altima,2.5 S,sedan,automatic,1N4AL3AP0FC216050,GA,38.0,16658.0,white,black,Enterprise Vehicle Exchange / Tra / Rental / T...,15100.0,11100.0,Thu Jul 09 2015 06:45:00 GMT-0700 (PDT)
558836,2014,Ford,F-150,XLT,SuperCrew,automatic,1FTFW1ET2EKE87277,CA,34.0,15008.0,gray,gray,Ford Motor Credit Company Llc Pd,29600.0,26700.0,Thu May 28 2015 05:30:00 GMT-0700 (PDT)

In [11]:
# Apply the title() method to each cell in the specified columns
df["Make"] = df["Make"].str.title()
df["Model"] = df["Model"].str.title()
df["Body"] = df["Body"].str.title()
df["Transmission"] = df["Transmission"].str.title()
df["Color"] = df["Color"].str.title()
df["Interior"] = df["Interior"].str.title()

In [12]:
df["Body"] = df["Body"].str.replace('Suv', 'SUV')

In [13]:
df["Make"] = df["Make"].str.upper()

In [14]:
df

,Year,Make,Model,Trim,Body,Transmission,VIN,State,Condition,Odometer,Color,Interior,Seller,MMR,Selling_Price,Sale_Date
0,2015,KIA,Sorento,LX,SUV,Automatic,5XYKTCA69FG566472,CA,5.0,16639.0,White,Black,Kia Motors America Inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,KIA,Sorento,LX,SUV,Automatic,5XYKTCA69FG561319,CA,5.0,9393.0,White,Beige,Kia Motors America Inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,Automatic,WBA3C1C51EK116351,CA,45.0,1331.0,Gray,Black,Financial Services Remarketing (Lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,VOLVO,S60,T5,Sedan,Automatic,YV1612TB4F1310987,CA,41.0,14282.0,White,Black,Volvo Na Rep/World Omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,Automatic,WBA6B2C57ED129731,CA,43.0,2641.0,Gray,Black,Financial Services Remarketing (Lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558832,2015,KIA,K900,Luxury,Sedan,NaN,KNALW4D4XF6019304,IN,45.0,18255.0,Silver,Black,Avis Corporation,35300.0,33000.0,Thu Jul 09 2015 07:00:00 GMT-0700 (PDT)
558833,2012,RAM,2500,Power Wagon,Crew Cab,Automatic,3C6TD5ET6CG112407,WA,5.0,54393.0,White,Black,I -5 Uhlmann Rv,30200.0,30800.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558834,2012,BMW,X5,xDrive35d,SUV,Automatic,5UXZW0C58CL668465,CA,48.0,50561.0,Black,Black,Financial Services Remarketing (Lease),29800.0,34000.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558835,2015,NISSAN,Altima,2.5 S,Sedan,Automatic,1N4AL3AP0FC216050,GA,38.0,16658.0,White,Black,Enterprise Vehicle Exchange / Tra / Rental / T...,15100.0,11100.0,Thu Jul 09 2015 06:45:00 GMT-0700 (PDT)
558836,2014,FORD,F-150,XLT,Supercrew,Automatic,1FTFW1ET2EKE87277,CA,34.0,15008.0,Gray,Gray,Ford Motor Credit Company Llc Pd,29600.0,26700.0,Thu May 28 2015 05:30:00 GMT-0700 (PDT)

In [15]:
#hecking VINs to identify NULLs and figure out what to do with them. 
#We see that 4 pcs of VINs were mistakenly inserted in the 'State' Column, so I will move them back into 'VIN' column
df[df["VIN"].isnull()]

,Year,Make,Model,Trim,Body,Transmission,VIN,State,Condition,Odometer,Color,Interior,Seller,MMR,Selling_Price,Sale_Date
461612,2015,VOLKSWAGEN,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,NaN,3VWD17AJ3FM259017,NaN,46.0,2711,White,Black,NaN,14250.0,14000
505299,2015,VOLKSWAGEN,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,NaN,3VWD17AJ7FM222388,NaN,36.0,20379,Silver,Black,NaN,13600.0,13500
529009,2015,VOLKSWAGEN,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,NaN,3VWD17AJ8FM298895,NaN,2.0,2817,Red,Black,NaN,13750.0,12200
551222,2015,VOLKSWAGEN,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,NaN,3VWD17AJ8FM239622,NaN,2.0,9562,Silver,Black,NaN,13200.0,12100

In [16]:
#After we've identified the indexes, we insert VINs into the 'VIN' column:
df.loc[461612, "VIN"] = "3VWD17AJ3FM259017"
df.loc[505299, "VIN"] = "3VWD17AJ7FM222388"
df.loc[529009, "VIN"] = "3VWD17AJ8FM298895"
df.loc[551222, "VIN"] = "3VWD17AJ8FM239622"

In [17]:
#and remove VINs from the 'State' column:
df.loc[505299, "State"] = ""
df.loc[529009, "State"] = ""
df.loc[551222, "State"] = ""
df.loc[461612, "State"] = ""

In [18]:
#Now removing rows where Sale_Date is not defined
df = df[df["Sale_Date"] != ""]

In [19]:
#Let's locate rows where number of characters in the 'State' column is more than two, it will show us which the list of indices where State values should be fixed. 
df.loc[df['State'].str.len() > 2].index

Index([408161, 417835, 421289, 424161, 427040, 427043, 434424, 444501, 453794,
       461597, 492484, 497008, 497011, 499083, 501455, 505306, 520461, 528996,
       529013, 529622, 548784, 554710],
      dtype='int64')

In [20]:
#We found that 22 VINS were mistakenly inserted into the 'State' column:
specific_indexes = [408161, 417835, 421289, 424161, 427040, 427043, 434424, 444501, 453794,
       461597, 492484, 497008, 497011, 499083, 501455, 505306, 520461, 528996,
       529013, 529622, 548784, 554710]

In [21]:
#Let's copy them from 'States' to 'VINs'
df.loc[specific_indexes, "VIN"] = df.loc[specific_indexes, "State"]

In [22]:
#And clean up the mess in the 'State' column
df.loc[specific_indexes, "State"] = ""

In [23]:
#A typical Sale_Date column is comprised of 39 characters, let's locate those, which contains less than 39:
df[df["Sale_Date"].str.len() < 39]
df.loc[df["Sale_Date"].str.len() < 39, "Sale_Date"] = ""

In [24]:
#Cleaning VINs containing / at the beginning
df["VIN"] = df["VIN"].str.lstrip("/")

In [25]:
df

,Year,Make,Model,Trim,Body,Transmission,VIN,State,Condition,Odometer,Color,Interior,Seller,MMR,Selling_Price,Sale_Date
0,2015,KIA,Sorento,LX,SUV,Automatic,5XYKTCA69FG566472,CA,5.0,16639.0,White,Black,Kia Motors America Inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,KIA,Sorento,LX,SUV,Automatic,5XYKTCA69FG561319,CA,5.0,9393.0,White,Beige,Kia Motors America Inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,Automatic,WBA3C1C51EK116351,CA,45.0,1331.0,Gray,Black,Financial Services Remarketing (Lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,VOLVO,S60,T5,Sedan,Automatic,YV1612TB4F1310987,CA,41.0,14282.0,White,Black,Volvo Na Rep/World Omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,Automatic,WBA6B2C57ED129731,CA,43.0,2641.0,Gray,Black,Financial Services Remarketing (Lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558832,2015,KIA,K900,Luxury,Sedan,NaN,KNALW4D4XF6019304,IN,45.0,18255.0,Silver,Black,Avis Corporation,35300.0,33000.0,Thu Jul 09 2015 07:00:00 GMT-0700 (PDT)
558833,2012,RAM,2500,Power Wagon,Crew Cab,Automatic,3C6TD5ET6CG112407,WA,5.0,54393.0,White,Black,I -5 Uhlmann Rv,30200.0,30800.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558834,2012,BMW,X5,xDrive35d,SUV,Automatic,5UXZW0C58CL668465,CA,48.0,50561.0,Black,Black,Financial Services Remarketing (Lease),29800.0,34000.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT)
558835,2015,NISSAN,Altima,2.5 S,Sedan,Automatic,1N4AL3AP0FC216050,GA,38.0,16658.0,White,Black,Enterprise Vehicle Exchange / Tra / Rental / T...,15100.0,11100.0,Thu Jul 09 2015 06:45:00 GMT-0700 (PDT)
558836,2014,FORD,F-150,XLT,Supercrew,Automatic,1FTFW1ET2EKE87277,CA,34.0,15008.0,Gray,Gray,Ford Motor Credit Company Llc Pd,29600.0,26700.0,Thu May 28 2015 05:30:00 GMT-0700 (PDT)

In [26]:
#Dropping nulls before splitting the column
df = df.dropna(subset = ["Sale_Date"])

In [27]:
#adding new column with a split Sale_Date
df["New_Sale_Date"] = df["Sale_Date"].apply(lambda x: x[0:10]+ '/' + x[11:15] + '/' + x[16:])

C:\Users\user\AppData\Local\Temp\ipykernel_9084\3373256063.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["New_Sale_Date"] = df["Sale_Date"].apply(lambda x: x[0:10]+ '/' + x[11:15] + '/' + x[16:])

In [28]:
#Extracting Year
df["Sale_Year"] = df['New_Sale_Date'].str.extract(r'/([^/]*)/')

C:\Users\user\AppData\Local\Temp\ipykernel_9084\1043057179.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Sale_Year"] = df['New_Sale_Date'].str.extract(r'/([^/]*)/')

In [29]:
#Extracting Day of Week
df['Sale_Day'] = df['New_Sale_Date'].str.slice(0,3)

C:\Users\user\AppData\Local\Temp\ipykernel_9084\3884834924.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sale_Day'] = df['New_Sale_Date'].str.slice(0,3)

In [30]:
#Extracting Month and Day
df["Sale_Month_And_Day"] = df['New_Sale_Date'].str.slice(4,10)

C:\Users\user\AppData\Local\Temp\ipykernel_9084\3312540583.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Sale_Month_And_Day"] = df['New_Sale_Date'].str.slice(4,10)

In [31]:
#Extracting time
df['Sale_Time'] = df['New_Sale_Date'].str.slice(17,)

C:\Users\user\AppData\Local\Temp\ipykernel_9084\1094131546.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sale_Time'] = df['New_Sale_Date'].str.slice(17,)

In [32]:
#Deleting New_Sale_Date column
df = df.drop(["New_Sale_Date"], axis=1)

In [33]:
df['Condition'] = pd.to_numeric(df['Condition'], errors='coerce')
df['Odometer'] = pd.to_numeric(df['Odometer'], errors='coerce')
df['MMR'] = pd.to_numeric(df['MMR'], errors='coerce')
df['Selling_Price'] = pd.to_numeric(df['Selling_Price'], errors='coerce').round()

In [34]:
#df_copy[df_copy["Transmission"] == "Sedan"]
df["Transmission"] = df["Transmission"].str.replace('Sedan', '')

In [35]:
#df_copy[df_copy["Color"]=="â€”"]
df["Color"] = df["Color"].str.replace('â€”', '')

In [36]:
df['Color'] = df['Color'].str.replace('[0-9]', '', regex = True)

In [37]:
df["Interior"] = df["Interior"].str.replace('â€”', '')

In [38]:
df.columns

Index(['Year', 'Make', 'Model', 'Trim', 'Body', 'Transmission', 'VIN', 'State',
       'Condition', 'Odometer', 'Color', 'Interior', 'Seller', 'MMR',
       'Selling_Price', 'Sale_Date', 'Sale_Year', 'Sale_Day',
       'Sale_Month_And_Day', 'Sale_Time'],
      dtype='object')

In [39]:
#Defining the list of columns where nulls will be replaced with ""
columns_to_fill= {
"Make":              "",
"Model":            "",
"Trim":             "",
"Body":             "",
"Transmission":     "",
"Condition":        "",
"Odometer":         "",
"Color":            "",
"Interior":         "",
"MMR":              "",
"Selling_Price":    "",
}

In [40]:
df.fillna(columns_to_fill, inplace=True)

In [44]:
#Final check for nulls
df.isnull().any()

Year                  False
Make                  False
Model                 False
Trim                  False
Body                  False
Transmission          False
VIN                   False
State                 False
Condition             False
Odometer              False
Color                 False
Interior              False
Seller                False
MMR                   False
Selling_Price         False
Sale_Date             False
Sale_Year             False
Sale_Day              False
Sale_Month_And_Day    False
Sale_Time             False
dtype: bool

In [42]:
df

,Year,Make,Model,Trim,Body,Transmission,VIN,State,Condition,Odometer,Color,Interior,Seller,MMR,Selling_Price,Sale_Date,Sale_Year,Sale_Day,Sale_Month_And_Day,Sale_Time
0,2015,KIA,Sorento,LX,SUV,Automatic,5XYKTCA69FG566472,CA,5.0,16639.0,White,Black,Kia Motors America Inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST),2014,Tue,Dec 16,2:30:00 GMT-0800 (PST)
1,2015,KIA,Sorento,LX,SUV,Automatic,5XYKTCA69FG561319,CA,5.0,9393.0,White,Beige,Kia Motors America Inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST),2014,Tue,Dec 16,2:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,Automatic,WBA3C1C51EK116351,CA,45.0,1331.0,Gray,Black,Financial Services Remarketing (Lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST),2015,Thu,Jan 15,4:30:00 GMT-0800 (PST)
3,2015,VOLVO,S60,T5,Sedan,Automatic,YV1612TB4F1310987,CA,41.0,14282.0,White,Black,Volvo Na Rep/World Omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST),2015,Thu,Jan 29,4:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,Automatic,WBA6B2C57ED129731,CA,43.0,2641.0,Gray,Black,Financial Services Remarketing (Lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST),2014,Thu,Dec 18,2:30:00 GMT-0800 (PST)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558832,2015,KIA,K900,Luxury,Sedan,,KNALW4D4XF6019304,IN,45.0,18255.0,Silver,Black,Avis Corporation,35300.0,33000.0,Thu Jul 09 2015 07:00:00 GMT-0700 (PDT),2015,Thu,Jul 09,7:00:00 GMT-0700 (PDT)
558833,2012,RAM,2500,Power Wagon,Crew Cab,Automatic,3C6TD5ET6CG112407,WA,5.0,54393.0,White,Black,I -5 Uhlmann Rv,30200.0,30800.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT),2015,Wed,Jul 08,9:30:00 GMT-0700 (PDT)
558834,2012,BMW,X5,xDrive35d,SUV,Automatic,5UXZW0C58CL668465,CA,48.0,50561.0,Black,Black,Financial Services Remarketing (Lease),29800.0,34000.0,Wed Jul 08 2015 09:30:00 GMT-0700 (PDT),2015,Wed,Jul 08,9:30:00 GMT-0700 (PDT)
558835,2015,NISSAN,Altima,2.5 S,Sedan,Automatic,1N4AL3AP0FC216050,GA,38.0,16658.0,White,Black,Enterprise Vehicle Exchange / Tra / Rental / T...,15100.0,11100.0,Thu Jul 09 2015 06:45:00 GMT-0700 (PDT),2015,Thu,Jul 09,6:45:00 GMT-0700 (PDT)
558836,2014,FORD,F-150,XLT,Supercrew,Automatic,1FTFW1ET2EKE87277,CA,34.0,15008.0,Gray,Gray,Ford Motor Credit Company Llc Pd,29600.0,26700.0,Thu May 28 2015 05:30:00 GMT-0700 (PDT),2015,Thu,May 28,5:30:00 GMT-0700 (PDT)

In [43]:
df.to_csv('Car_prices_clean.csv', index=False)